#!/usr/bin/env bash

set -u

repo_dir="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
bin_dir="${XDG_BIN_HOME:-$HOME/.local/bin}"
selectors_dir="$config_home/rice-theme/selectors"
systemd_user_dir="$config_home/systemd/user"
thunar_dir="$repo_dir/config/thunar"
icon_theme_dir="$repo_dir/config/icons/GhostShell"
errors=0
missing=0
install_packages=true

case "${1:-}" in
    '') ;;
    --skip-package-install) install_packages=false ;;
    *) printf 'Usage: %s [--skip-package-install]\n' "$0" >&2; exit 2 ;;
esac

ok() { printf 'OK       %s\n' "$*"; }
warn() { printf 'WARNING  %s\n' "$*" >&2; }
fail() { printf 'CONFLICT %s\n' "$*" >&2; errors=$((errors + 1)); }

ensure_link() {
    local source="$1" destination="$2"
    mkdir -p -- "${destination%/*}"
    if [[ -L "$destination" ]] &&
       [[ "$(readlink -f -- "$destination" 2>/dev/null)" == "$(readlink -f -- "$source")" ]]; then
        ok "$destination"
    elif [[ -e "$destination" || -L "$destination" ]]; then
        fail "$destination already exists and is not the managed link"
        return 1
    elif ln -s -- "$source" "$destination"; then
        ok "$destination -> $source"
    else
        fail "could not create $destination"
        return 1
    fi
}

migrate_moved_link() {
    local old_source="$1" source="$2" destination="$3"
    if [[ -L "$destination" && "$(readlink -- "$destination")" == "$old_source" ]]; then
        if ln -sfn -- "$source" "$destination"; then
            ok "$destination -> $source (migrated)"
        else
            fail "could not migrate $destination"
        fi
    fi
}

migrate_managed_service_mask() {
    local unit="$1" mask
    mask="$systemd_user_dir/$unit"
    if [[ -L "$mask" && "$(readlink -- "$mask")" == /dev/null ]]; then
        if rm -- "$mask"; then
            ok "removed obsolete $unit mask"
        else
            fail "could not remove obsolete $unit mask"
        fi
    fi
}

remove_obsolete_managed_link() {
    local old_source="$1" destination="$2"
    if [[ -L "$destination" && "$(readlink -- "$destination")" == "$old_source" ]]; then
        if rm -- "$destination"; then
            ok "removed obsolete managed link: $destination"
        else
            fail "could not remove obsolete managed link: $destination"
        fi
    fi
}

read_default() {
    local app_dir="$1" kind="$2" name
    [[ -r "$app_dir/default-theme" ]] || { fail "missing $kind default-theme"; return 1; }
    IFS= read -r name < "$app_dir/default-theme"
    [[ "$name" =~ ^[A-Za-z0-9_-]+$ ]] || { fail "invalid $kind default theme: $name"; return 1; }
    printf '%s\n' "$name"
}

initialize_kitty_theme() {
    local app_dir="$config_home/kitty" selector="$selectors_dir/kitty.conf"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/kitty" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Kitty local theme already initialized"; return; }
    name="$(read_default "$app_dir" Kitty)" || return
    [[ -f "$app_dir/themes/$name.conf" ]] || { fail "missing Kitty default theme file: $name"; return; }
    temp=$(mktemp "$selectors_dir/.kitty.conf.XXXXXX") || { fail 'could not create Kitty selector'; return; }
    printf '%s\n' '# Local theme selection; generated by setup.sh or kitty-theme.' \
        "include $app_dir/themes/$name.conf" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Kitty theme: $name"
}

initialize_rofi_theme() {
    local app_dir="$config_home/rofi" selector="$selectors_dir/rofi.rasi"
    local name target temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/rofi" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Rofi local theme already initialized"; return; }
    name="$(read_default "$app_dir" Rofi)" || return
    target="$app_dir/themes/$name/theme.rasi"
    [[ -f "$target" ]] || { fail "missing Rofi default theme: $name"; return; }
    temp=$(mktemp "$selectors_dir/.rofi.rasi.XXXXXX") || { fail 'could not create Rofi selector'; return; }
    printf '@theme "%s"\n' "$target" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Rofi theme: $name"
}

initialize_waybar_theme() {
    local app_dir="$config_home/waybar" selector="$selectors_dir/waybar.css"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/waybar" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Waybar local theme already initialized"; return; }
    name="$(read_default "$app_dir" Waybar)" || return
    [[ -f "$app_dir/themes/$name.css" ]] || { fail "missing Waybar default theme: $name"; return; }
    temp=$(mktemp "$selectors_dir/.waybar.css.XXXXXX") || { fail 'could not create Waybar selector'; return; }
    printf '@import url("../../waybar/themes/%s.css");\n' "$name" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Waybar theme: $name"
}

initialize_hyprland_theme() {
    local app_dir="$config_home/hypr" selector="$selectors_dir/hyprland.conf"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/hypr" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Hyprland local theme already initialized"; return; }
    name="$(read_default "$app_dir" Hyprland)" || return
    [[ -f "$app_dir/themes/$name.conf" ]] || { fail "missing Hyprland default theme file: $name"; return; }
    temp=$(mktemp "$selectors_dir/.hyprland.conf.XXXXXX") || { fail 'could not create Hyprland selector'; return; }
    printf 'source = %s/themes/%s.conf\n' "$app_dir" "$name" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Hyprland theme: $name"
}

initialize_swaync_theme() {
    local app_dir="$config_home/swaync" selector="$selectors_dir/swaync.css"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/swaync" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "SwayNC local theme already initialized"; return; }
    name="$(read_default "$app_dir" SwayNC)" || return
    [[ -f "$app_dir/themes/$name.css" ]] || { fail "missing SwayNC default theme file: $name"; return; }
    temp=$(mktemp "$selectors_dir/.swaync.css.XXXXXX") || { fail 'could not create SwayNC selector'; return; }
    printf '@import url("../../swaync/themes/%s.css");\n' "$name" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized SwayNC theme: $name"
}

initialize_rice_theme() {
    local app_dir="$config_home/rice-theme" selector="$selectors_dir/profile"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/rice-theme" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "desktop profile already initialized"; return; }
    [[ -r "$app_dir/default-profile" ]] || { fail 'missing default desktop profile'; return; }
    IFS= read -r name < "$app_dir/default-profile"
    [[ "$name" =~ ^[A-Za-z0-9_-]+$ && -f "$app_dir/profiles/$name" ]] || {
        fail "invalid default desktop profile: $name"
        return
    }
    temp=$(mktemp "$selectors_dir/.profile.XXXXXX") || { fail 'could not create desktop profile selector'; return; }
    printf '%s\n' "$name" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized desktop profile: $name"
}

migrate_theme_selector() {
    local kind="$1" old_selector="$2" selector="$3" app_dir="$4" managed_dir="$5"
    local name theme_path temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$managed_dir" ]] || return
    [[ -f "$old_selector" && ! -e "$selector" && ! -L "$selector" ]] || return
    case "$kind" in
        Hyprland)
            name=$(sed -n 's|^[[:space:]]*source[[:space:]]*=[[:space:]]*.*themes/\([A-Za-z0-9_-]*\)\.conf[[:space:]]*$|\1|p' "$old_selector")
            theme_path="$app_dir/themes/$name.conf"
            ;;
        Kitty)
            theme_path=$(awk '$1 == "include" { print $2; exit }' "$old_selector")
            name=$(basename "${theme_path:-}" .conf)
            [[ "$name" == black ]] && name=ghost-shell
            theme_path="$app_dir/themes/$name.conf"
            ;;
        Rofi)
            theme_path=$(sed -n 's/^@theme[[:space:]]*"\(.*\)"$/\1/p' "$old_selector")
            name=$(basename "$(dirname "${theme_path:-/}")")
            [[ "$name" == ghost-v2 ]] && name=ghost-shell
            theme_path="$app_dir/themes/$name/theme.rasi"
            ;;
        Waybar|SwayNC)
            name=$(sed -n 's|^@import url("themes/\([A-Za-z0-9_-]*\)\.css");$|\1|p' "$old_selector")
            theme_path="$app_dir/themes/$name.css"
            ;;
    esac
    [[ "$name" =~ ^[A-Za-z0-9_-]+$ && -f "$theme_path" ]] || {
        warn "could not migrate invalid $kind selector: $old_selector"
        return
    }
    temp=$(mktemp "$selectors_dir/.selector.XXXXXX") || { fail "could not migrate $kind selector"; return; }
    case "$kind" in
        Hyprland) printf 'source = %s\n' "$theme_path" > "$temp" ;;
        Kitty) printf '%s\n' '# Local theme selection; generated by setup.sh or kitty-theme.' "include $theme_path" > "$temp" ;;
        Rofi) printf '@theme "%s"\n' "$theme_path" > "$temp" ;;
        Waybar) printf '@import url("../../waybar/themes/%s.css");\n' "$name" > "$temp" ;;
        SwayNC) printf '@import url("../../swaync/themes/%s.css");\n' "$name" > "$temp" ;;
    esac
    if mv -- "$temp" "$selector" && rm -f -- "$old_selector"; then
        ok "migrated $kind selector to $selector"
    else
        rm -f -- "$temp"
        fail "could not migrate $kind selector"
    fi
}

migrate_local_selectors() {
    migrate_theme_selector Hyprland "$config_home/hypr/local-theme.conf" "$selectors_dir/hyprland.conf" "$config_home/hypr" "$repo_dir/config/hypr"
    migrate_theme_selector Kitty "$config_home/kitty/local-theme.conf" "$selectors_dir/kitty.conf" "$config_home/kitty" "$repo_dir/config/kitty"
    migrate_theme_selector Rofi "$config_home/rofi/local-theme.rasi" "$selectors_dir/rofi.rasi" "$config_home/rofi" "$repo_dir/config/rofi"
    migrate_theme_selector Waybar "$config_home/waybar/local-theme.css" "$selectors_dir/waybar.css" "$config_home/waybar" "$repo_dir/config/waybar"
    migrate_theme_selector SwayNC "$config_home/swaync/local-theme.css" "$selectors_dir/swaync.css" "$config_home/swaync" "$repo_dir/config/swaync"
    if [[ -f "$config_home/rice-theme/local-profile" && ! -e "$selectors_dir/profile" ]]; then
        if mv -- "$config_home/rice-theme/local-profile" "$selectors_dir/profile"; then
            ok "migrated desktop profile selector to $selectors_dir/profile"
        else
            fail 'could not migrate desktop profile selector'
        fi
    fi
}

check_command() {
    local command_name="$1" feature="$2"
    if command -v "$command_name" >/dev/null 2>&1; then
        ok "$command_name ($feature)"
    else
        warn "missing command: $command_name ($feature)"
        missing=$((missing + 1))
    fi
}

package_installed() {
    [[ "$(dpkg-query -W -f='${db:Status-Abbrev}' "$1" 2>/dev/null)" == ii* ]]
}

install_file_manager_packages() {
    local package
    local -a required_packages=(
        thunar thunar-archive-plugin thunar-volman tumbler
        gvfs gvfs-backends gvfs-fuse libmtp-runtime udisks2
        file-roller 7zip kitty desktop-file-utils xdg-user-dirs xdg-utils
        xfconf libglib2.0-bin python3 adwaita-icon-theme
    )
    local -a missing_packages=()

    if ! command -v dpkg-query >/dev/null 2>&1 || ! command -v apt-get >/dev/null 2>&1; then
        fail 'automatic file-manager package installation requires Ubuntu/Debian apt and dpkg'
        return
    fi
    for package in "${required_packages[@]}"; do
        package_installed "$package" || missing_packages+=("$package")
    done
    if (( ${#missing_packages[@]} == 0 )); then
        ok 'file-manager packages already installed'
        return
    fi

    printf 'Installing missing file-manager packages: %s\n' "${missing_packages[*]}"
    if (( EUID == 0 )); then
        apt-get install -y -- "${missing_packages[@]}" || fail 'could not install file-manager packages'
    elif command -v sudo >/dev/null 2>&1; then
        sudo apt-get install -y -- "${missing_packages[@]}" || fail 'could not install file-manager packages'
    else
        fail "missing file-manager packages and sudo is unavailable: ${missing_packages[*]}"
    fi
}

apply_thunar_xfconf() {
    local channel property type value
    if ! command -v xfconf-query >/dev/null 2>&1; then
        fail 'cannot apply Thunar settings: xfconf-query is unavailable'
        return
    fi
    while read -r channel property type value; do
        [[ -n "${channel:-}" && "$channel" != \#* ]] || continue
        if xfconf-query --channel "$channel" --property "$property" >/dev/null 2>&1; then
            xfconf-query --channel "$channel" --property "$property" --set "$value" \
                || fail "could not set $channel:$property"
        else
            xfconf-query --channel "$channel" --property "$property" \
                --create --type "$type" --set "$value" \
                || fail "could not create $channel:$property"
        fi
    done < "$thunar_dir/xfconf.settings"
    ok 'applied intentional Thunar and volume-manager settings'
}

merge_thunar_custom_actions() {
    local destination="$config_home/Thunar/uca.xml"
    command -v python3 >/dev/null 2>&1 || {
        fail 'cannot merge Thunar custom actions: python3 is unavailable'
        return
    }
    mkdir -p -- "${destination%/*}"
    if python3 - "$thunar_dir/uca.xml" "$destination" <<'PY'
import os
import sys
import tempfile
import xml.etree.ElementTree as ET

managed_path, destination = sys.argv[1:]
managed_root = ET.parse(managed_path).getroot()
if os.path.exists(destination):
    root = ET.parse(destination).getroot()
else:
    root = ET.Element("actions")

managed_ids = {
    action.findtext("unique-id")
    for action in managed_root.findall("action")
}
for action in list(root.findall("action")):
    action_id = action.findtext("unique-id")
    command = action.findtext("command", "")
    description = action.findtext("description", "")
    legacy_terminal = (
        action.findtext("name") == "Open Terminal Here"
        and "exo-open" in command
        and description == "Example for a custom action"
    )
    if action_id in managed_ids or legacy_terminal:
        root.remove(action)

for action in managed_root.findall("action"):
    root.append(action)

tree = ET.ElementTree(root)
ET.indent(tree, space="  ")
directory = os.path.dirname(destination)
fd, temporary = tempfile.mkstemp(prefix=".uca.xml.", dir=directory)
try:
    with os.fdopen(fd, "wb") as stream:
        tree.write(stream, encoding="UTF-8", xml_declaration=True)
    os.replace(temporary, destination)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY
    then
        ok 'merged managed Thunar custom actions'
    else
        fail 'could not merge managed Thunar custom actions'
    fi
}

configure_thunar_bookmarks() {
    local destination="$config_home/gtk-3.0/bookmarks"
    command -v python3 >/dev/null 2>&1 || {
        fail 'cannot configure Thunar bookmarks: python3 is unavailable'
        return
    }
    mkdir -p -- "${destination%/*}"
    if python3 - "$destination" <<'PY'
import os
from pathlib import Path
import subprocess
import sys
import tempfile

destination = sys.argv[1]

def user_dir(name):
    result = subprocess.run(
        ["xdg-user-dir", name], check=True, capture_output=True, text=True
    ).stdout.strip()
    return Path(result).expanduser().resolve().as_uri()

managed = {name: user_dir(name) for name in (
    "DESKTOP", "DOCUMENTS", "DOWNLOAD", "MUSIC", "PICTURES", "VIDEOS"
)}
desired = [managed[name] for name in ("DOCUMENTS", "DOWNLOAD", "PICTURES")]
existing = []
if os.path.exists(destination):
    with open(destination, encoding="utf-8") as stream:
        existing = [line.rstrip("\n") for line in stream if line.strip()]

managed_uris = set(managed.values())
unmanaged = [line for line in existing if line.split(" ", 1)[0] not in managed_uris]
lines = desired + unmanaged
directory = os.path.dirname(destination)
fd, temporary = tempfile.mkstemp(prefix=".bookmarks.", dir=directory, text=True)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines) + ("\n" if lines else ""))
    os.replace(temporary, destination)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY
    then
        ok 'configured core Thunar bookmarks; preserved unrelated bookmarks'
    else
        fail 'could not configure core Thunar bookmarks'
    fi
}

hide_thunar_desktop_shortcut() {
    command -v python3 >/dev/null 2>&1 || {
        fail 'cannot hide the Thunar Desktop shortcut: python3 is unavailable'
        return
    }
    if python3 - <<'PY'
from pathlib import Path
import subprocess

desktop = subprocess.run(
    ["xdg-user-dir", "DESKTOP"], check=True, capture_output=True, text=True
).stdout.strip()
desktop_uri = Path(desktop).expanduser().resolve().as_uri()
query = ["xfconf-query", "--channel", "thunar", "--property", "/hidden-bookmarks"]
current = subprocess.run(query, capture_output=True, text=True)
values = current.stdout.splitlines() if current.returncode == 0 else []
if values and values[0].startswith("Value is an array"):
    values = values[1:]
values = [value for value in values if value]
if desktop_uri not in values:
    values.append(desktop_uri)

command = query.copy()
if current.returncode != 0:
    command.append("--create")
command.append("--force-array")
for value in values:
    command.extend(("--type", "string", "--set", value))
subprocess.run(command, check=True)
PY
    then
        ok 'hid the native Thunar Desktop shortcut; preserved other hidden shortcuts'
    else
        fail 'could not hide the native Thunar Desktop shortcut'
    fi
}

apply_file_manager_mime_defaults() {
    local section=false mime desktop
    if ! command -v xdg-mime >/dev/null 2>&1; then
        fail 'cannot apply file-manager MIME defaults: xdg-mime is unavailable'
        return
    fi
    while IFS= read -r line; do
        case "$line" in
            '[Default Applications]') section=true; continue ;;
            '['*) section=false; continue ;;
            ''|'#'*) continue ;;
        esac
        "$section" || continue
        mime="${line%%=*}"
        desktop="${line#*=}"
        desktop="${desktop%;}"
        xdg-mime default "$desktop" "$mime" || fail "could not set MIME default for $mime"
    done < "$thunar_dir/mimeapps.list"
    ok 'applied file-manager MIME defaults without replacing unrelated associations'
}

apply_media_handling_policy() {
    if ! command -v gsettings >/dev/null 2>&1; then
        fail 'cannot apply media handling policy: gsettings is unavailable'
        return
    fi
    gsettings set org.gnome.desktop.media-handling automount true \
        || fail 'could not enable media automount'
    gsettings set org.gnome.desktop.media-handling automount-open false \
        || fail 'could not disable opening a window after automount'
    gsettings set org.gnome.desktop.media-handling autorun-never true \
        || fail 'could not disable media autorun'
    ok 'applied safe desktop media handling policy'
}

apply_gtk_appearance_policy() {
    if ! command -v gsettings >/dev/null 2>&1; then
        fail 'cannot apply GTK appearance policy: gsettings is unavailable'
        return
    fi
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark \
        || fail 'could not enable the dark GTK color scheme'
    gsettings set org.gnome.desktop.interface icon-theme GhostShell \
        || fail 'could not select the Ghost Shell icon theme'
    if gsettings range org.gnome.desktop.interface accent-color >/dev/null 2>&1; then
        gsettings set org.gnome.desktop.interface accent-color blue \
            || fail 'could not set the native blue GTK accent'
    fi
    if python3 - "$config_home/gtk-3.0/settings.ini" <<'PY'
import os
import sys
import tempfile

destination = sys.argv[1]
lines = []
if os.path.exists(destination):
    with open(destination, encoding="utf-8") as stream:
        lines = stream.read().splitlines()

section = next((index for index, line in enumerate(lines) if line.strip() == "[Settings]"), None)
if section is None:
    if lines and lines[-1]:
        lines.append("")
    lines.extend(("[Settings]", "gtk-icon-theme-name=GhostShell"))
else:
    end = next(
        (index for index in range(section + 1, len(lines)) if lines[index].strip().startswith("[")),
        len(lines),
    )
    setting = next(
        (index for index in range(section + 1, end) if lines[index].split("=", 1)[0].strip() == "gtk-icon-theme-name"),
        None,
    )
    if setting is None:
        lines.insert(end, "gtk-icon-theme-name=GhostShell")
    else:
        lines[setting] = "gtk-icon-theme-name=GhostShell"

directory = os.path.dirname(destination)
os.makedirs(directory, exist_ok=True)
fd, temporary = tempfile.mkstemp(prefix=".settings.ini.", dir=directory, text=True)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines) + "\n")
    os.replace(temporary, destination)
finally:
    if os.path.exists(temporary):
        os.unlink(temporary)
PY
    then
        ok 'applied native dark GTK, blue accent, and minimal icon-theme preferences'
    else
        fail 'could not apply the GTK 3 icon-theme preference'
    fi
}

printf 'Deploying rice-config from %s\n\n' "$repo_dir"

if "$install_packages"; then
    install_file_manager_packages
else
    warn 'skipping file-manager package installation by request'
fi

ensure_link "$repo_dir/config/hypr" "$config_home/hypr"
ensure_link "$repo_dir/config/kitty" "$config_home/kitty"
ensure_link "$repo_dir/config/rofi" "$config_home/rofi"
ensure_link "$repo_dir/config/waybar" "$config_home/waybar"
ensure_link "$repo_dir/config/swaync" "$config_home/swaync"
remove_obsolete_managed_link "$repo_dir/config/wlogout" "$config_home/wlogout"
ensure_link "$repo_dir/config/rice-theme" "$config_home/rice-theme"
ensure_link "$icon_theme_dir" "$data_home/icons/GhostShell"
ensure_link "$thunar_dir/tumbler.rc" "$config_home/tumbler/tumbler.rc"

migrate_managed_service_mask waybar.service
migrate_managed_service_mask swaync.service
remove_obsolete_managed_link \
    "$repo_dir/config/systemd/user/waybar.service.d/rice-config.conf" \
    "$systemd_user_dir/waybar.service.d/rice-config.conf"
migrate_moved_link \
    "$repo_dir/config/systemd/user/waybar.service" \
    "$repo_dir/config/waybar/waybar.service" \
    "$systemd_user_dir/waybar.service"
migrate_moved_link \
    "$repo_dir/config/systemd/user/swaync.service.d/rice-config.conf" \
    "$repo_dir/config/swaync/swaync.service.conf" \
    "$systemd_user_dir/swaync.service.d/rice-config.conf"
ensure_link "$repo_dir/config/waybar/waybar.service" \
    "$systemd_user_dir/waybar.service"
ensure_link "$repo_dir/config/swaync/swaync.service.conf" \
    "$systemd_user_dir/swaync.service.d/rice-config.conf"
ensure_link "$repo_dir/config/systemd/user/hyprland-session.target" \
    "$systemd_user_dir/hyprland-session.target"
remove_obsolete_managed_link \
    "$repo_dir/config/pipewire/pipewire-pulse.conf.d/50-spotify-icon.conf" \
    "$config_home/pipewire/pipewire-pulse.conf.d/50-spotify-icon.conf"
ensure_link "$repo_dir/config/swaync/spotify.conf" \
    "$config_home/pipewire/pipewire-pulse.conf.d/swaync-spotify.conf"
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload || fail 'could not reload systemd user units'
fi

migrate_moved_link "$repo_dir/scripts/kitty-theme.sh" "$repo_dir/scripts/theme-selector/kitty-theme.sh" "$bin_dir/kitty-theme"
migrate_moved_link "$repo_dir/scripts/rofi-theme.sh" "$repo_dir/scripts/theme-selector/rofi-theme.sh" "$bin_dir/rofi-theme"
migrate_moved_link "$repo_dir/scripts/waybar-theme.sh" "$repo_dir/scripts/theme-selector/waybar-theme.sh" "$bin_dir/waybar-theme"
migrate_moved_link "$repo_dir/scripts/hyprland-theme.sh" "$repo_dir/scripts/theme-selector/hyprland-theme.sh" "$bin_dir/hyprland-theme"
migrate_moved_link "$repo_dir/scripts/swaync-theme.sh" "$repo_dir/scripts/theme-selector/swaync-theme.sh" "$bin_dir/swaync-theme"
migrate_moved_link "$repo_dir/scripts/rice-theme.sh" "$repo_dir/scripts/theme-selector/rice-theme.sh" "$bin_dir/rice-theme"

ensure_link "$repo_dir/scripts/keybind-help" "$bin_dir/keybind-help"
ensure_link "$repo_dir/scripts/theme-selector/kitty-theme.sh" "$bin_dir/kitty-theme"
ensure_link "$repo_dir/scripts/theme-selector/rofi-theme.sh" "$bin_dir/rofi-theme"
ensure_link "$repo_dir/scripts/waybar-nvidia" "$bin_dir/waybar-nvidia"
ensure_link "$repo_dir/scripts/waybar-microphone" "$bin_dir/waybar-microphone"
ensure_link "$repo_dir/scripts/waycal-toggle" "$bin_dir/waycal-toggle"
ensure_link "$repo_dir/scripts/theme-selector/waybar-theme.sh" "$bin_dir/waybar-theme"
ensure_link "$repo_dir/scripts/theme-selector/hyprland-theme.sh" "$bin_dir/hyprland-theme"
ensure_link "$repo_dir/scripts/theme-selector/swaync-theme.sh" "$bin_dir/swaync-theme"
ensure_link "$repo_dir/scripts/theme-selector/rice-theme.sh" "$bin_dir/rice-theme"
ensure_link "$repo_dir/scripts/waybar-swaync" "$bin_dir/waybar-swaync"
ensure_link "$repo_dir/scripts/rofi-apps" "$bin_dir/rofi-apps"
ensure_link "$repo_dir/scripts/idle-suspend" "$bin_dir/idle-suspend"
ensure_link "$repo_dir/scripts/power-menu" "$bin_dir/power-menu"

ensure_link "$repo_dir/config/rofi/hidden-applications.desktop" \
    "$data_home/applications/rofi-hidden-applications.desktop"
ensure_link "$repo_dir/config/rofi/system-applications.desktop" \
    "$data_home/applications/rofi-system-applications.desktop"

if [[ "$(readlink -f -- "$config_home/rice-theme" 2>/dev/null)" == "$repo_dir/config/rice-theme" ]]; then
    if mkdir -p -- "$selectors_dir"; then
        migrate_local_selectors
    else
        fail "could not create selector directory: $selectors_dir"
    fi
fi
initialize_hyprland_theme
initialize_kitty_theme
initialize_rofi_theme
initialize_waybar_theme
initialize_swaync_theme
initialize_rice_theme

if [[ "$(readlink -f -- "$config_home/rofi" 2>/dev/null)" == "$repo_dir/config/rofi" ]]; then
    "$config_home/rofi/scripts/hidden-apps.sh" sync || fail 'could not synchronize Hidden applications'
    "$config_home/rofi/scripts/system-apps.sh" sync || fail 'could not synchronize System applications'
fi

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$data_home/applications" \
        || fail 'could not refresh the user desktop-entry database'
fi
apply_thunar_xfconf
merge_thunar_custom_actions
configure_thunar_bookmarks
hide_thunar_desktop_shortcut
apply_file_manager_mime_defaults
apply_media_handling_policy
apply_gtk_appearance_policy

printf '\nDependency check\n'
for item in \
    'Hyprland:desktop compositor' 'hyprctl:Hyprland control' 'kitty:terminal' \
    'rofi:application launcher' 'hypridle:idle handling' 'hyprlock:screen locking' \
    'waybar:desktop panel' 'swaync:notification daemon' 'swaync-client:notification controls' \
    'wlctl:Wi-Fi control' 'nmtui:Ethernet control' 'bluetui:Bluetooth control' \
    'wiremix:audio control' 'pipewire-pulse:PulseAudio compatibility' 'pw-dump:microphone state' 'wpctl:audio mute control' \
    'powerprofilesctl:power profile control' \
    'swayosd-server:on-screen display' 'swayosd-client:media and hardware keys' \
    'playerctl:media control' 'brightnessctl:brightness control' 'thunar:file manager' \
    'file-roller:archive manager' '7z:7z and RAR archive support' 'udisksctl:removable storage' \
    'loupe:image viewing' 'papers:PDF viewing' 'gnome-text-editor:plain-text editing' \
    'code:development-file editing' 'mpv:audio and video playback' 'google-chrome:web links' \
    'xfconf-query:Thunar settings' 'xdg-mime:MIME defaults' 'gsettings:desktop media and appearance settings' \
    'python3:state-preserving configuration merges' 'update-desktop-database:desktop-entry cache updates' \
    'jq:JSON processing' \
    'gio:desktop-entry launching' 'hyprshot:screenshots (external)' 'grim:screenshot capture' \
    'slurp:geometry selection' 'wl-copy:clipboard screenshots' 'notify-send:notifications' \
    'xdg-user-dir:pictures directory'; do
    check_command "${item%%:*}" "${item#*:}"
done
if command -v hyprpolkitagent >/dev/null 2>&1 || [[ -x /usr/libexec/hyprpolkitagent ]]; then
    ok 'Hyprland polkit agent'
else
    warn 'missing Hyprland polkit agent executable'
    missing=$((missing + 1))
fi
if command -v qtpaths6 >/dev/null 2>&1 &&
   [[ -f "$(qtpaths6 --query QT_INSTALL_QML)/org/hyprland/style/qmldir" ]]; then
    ok 'Hyprland Qt/QML style module'
else
    warn 'missing Hyprland Qt/QML style module: org.hyprland.style'
    missing=$((missing + 1))
fi
command -v hyprpicker >/dev/null 2>&1 || warn 'optional command missing: hyprpicker (Hyprshot freeze mode)'
command -v waycal >/dev/null 2>&1 || warn 'optional command missing: waycal (Waybar clock calendar; install the official release binary on PATH)'
case ":$PATH:" in
    *:"$bin_dir":*) ;;
    *) warn "$bin_dir is not on PATH; desktop gateway commands will not launch" ;;
esac

printf '\nValidation\n'
if command -v python3 >/dev/null 2>&1; then
    if python3 -c 'import sys, xml.etree.ElementTree as ET; ET.parse(sys.argv[1])' \
        "$thunar_dir/uca.xml"; then
        ok 'Thunar custom-action XML'
    else
        fail 'Thunar custom-action XML validation failed'
    fi
fi
if awk '
    NF && $1 !~ /^#/ && NF != 4 { bad=1 }
    END { exit bad }
' "$thunar_dir/xfconf.settings"; then
    ok 'Thunar xfconf declarations'
else
    fail 'Thunar xfconf declaration validation failed'
fi
if awk '
    /^\[Default Applications\]$/ { section=1; next }
    /^\[/ { section=0 }
    section && NF && $0 !~ /^#/ && $0 !~ /^[^=]+=.+\.desktop$/ { bad=1 }
    END { exit bad }
' "$thunar_dir/mimeapps.list"; then
    ok 'file-manager MIME declarations'
else
    fail 'file-manager MIME declaration validation failed'
fi
if command -v desktop-file-validate >/dev/null 2>&1; then
    if desktop-file-validate "$repo_dir/config/rofi/hidden-applications.desktop" \
        "$repo_dir/config/rofi/system-applications.desktop"; then
        ok 'Rofi gateway desktop entries'
    else
        fail 'Rofi gateway desktop-entry validation failed'
    fi
fi
if command -v Hyprland >/dev/null 2>&1 && [[ -r "$config_home/hypr/hyprland.conf" ]]; then
    if Hyprland --verify-config --config "$config_home/hypr/hyprland.conf" >/dev/null 2>&1; then
        ok 'Hyprland configuration'
    else
        fail 'Hyprland configuration validation failed'
    fi
fi
kitty_validation=""
if command -v kitty >/dev/null 2>&1 && [[ -r "$config_home/kitty/kitty.conf" ]]; then
    if kitty_validation=$(KITTY_CONFIG_TO_CHECK="$config_home/kitty/kitty.conf" kitty +runpy '
import os, sys
from kitty.config import load_config
b = []
load_config(os.environ["KITTY_CONFIG_TO_CHECK"], accumulate_bad_lines=b)
sys.exit(bool(b))
' 2>&1) && [[ -z "$kitty_validation" ]]; then
        ok 'Kitty configuration'
    else
        [[ -z "$kitty_validation" ]] || warn "Kitty configuration diagnostics: $kitty_validation"
        fail 'Kitty configuration validation failed'
    fi
fi
if command -v rofi >/dev/null 2>&1 && [[ -r "$config_home/rofi/config.rasi" ]]; then
    if rofi -config "$config_home/rofi/config.rasi" -dump-config >/dev/null 2>&1; then
        ok 'Rofi configuration'
    else
        fail 'Rofi configuration validation failed'
    fi
fi
if [[ -r "$config_home/waybar/config.jsonc" ]] &&
   [[ "$(readlink -f -- "$config_home/waybar" 2>/dev/null)" == "$repo_dir/config/waybar" ]]; then
    waybar_json_valid=true
    if command -v json5 >/dev/null 2>&1; then
        for waybar_json in "$config_home/waybar/config.jsonc" "$config_home/waybar/modules/"*.jsonc; do
            json5 --validate "$waybar_json" >/dev/null 2>&1 || waybar_json_valid=false
        done
    elif command -v jq >/dev/null 2>&1; then
        jq empty "$config_home/waybar/config.jsonc" "$config_home/waybar/modules/"*.jsonc || waybar_json_valid=false
    else
        waybar_json_valid=false
    fi
    if "$waybar_json_valid"; then
        ok 'Waybar JSONC configuration'
    else
        fail 'Waybar JSONC configuration validation failed'
    fi

    if command -v python3 >/dev/null 2>&1 &&
       python3 -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk' >/dev/null 2>&1; then
        if python3 -c 'import gi, sys; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk; provider = Gtk.CssProvider(); provider.load_from_path(sys.argv[1])' "$config_home/waybar/style.css"; then
            ok 'Waybar GTK3 stylesheet'
        else
            fail 'Waybar GTK3 stylesheet validation failed'
        fi
    else
        fail 'cannot validate Waybar GTK3 stylesheet: Python GObject GTK3 bindings unavailable'
    fi
fi
if [[ -r "$config_home/swaync/config.json" ]] &&
   [[ "$(readlink -f -- "$config_home/swaync" 2>/dev/null)" == "$repo_dir/config/swaync" ]]; then
    swaync_json_valid=false
    if command -v json5 >/dev/null 2>&1; then
        json5 --validate "$config_home/swaync/config.json" >/dev/null 2>&1 && swaync_json_valid=true
    elif command -v jq >/dev/null 2>&1; then
        jq empty "$config_home/swaync/config.json" >/dev/null 2>&1 && swaync_json_valid=true
    fi
    if "$swaync_json_valid"; then
        ok 'SwayNC JSON configuration'
    else
        fail 'SwayNC JSON configuration validation failed'
    fi
    if command -v python3 >/dev/null 2>&1 &&
       python3 -c 'import gi; gi.require_version("Gtk", "4.0"); from gi.repository import Gtk' >/dev/null 2>&1; then
        if python3 -c 'import gi, sys; gi.require_version("Gtk", "4.0"); from gi.repository import Gtk; provider = Gtk.CssProvider(); provider.load_from_path(sys.argv[1])' "$config_home/swaync/style.css"; then
            ok 'SwayNC GTK4 stylesheet'
        else
            fail 'SwayNC GTK4 stylesheet validation failed'
        fi
    else
        fail 'cannot validate SwayNC GTK4 stylesheet: Python GObject GTK4 bindings unavailable'
    fi
fi
printf '\n'
if (( errors )); then
    printf 'Deployment completed with %d conflict/error(s).\n' "$errors" >&2
    exit 1
fi
printf 'Deployment complete. Missing dependency count: %d.\n' "$missing"
