#!/usr/bin/env bash

set -u

repo_dir="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
bin_dir="${XDG_BIN_HOME:-$HOME/.local/bin}"
errors=0
missing=0

ok() { printf 'OK       %s\n' "$*"; }
warn() { printf 'WARNING  %s\n' "$*" >&2; }
fail() { printf 'CONFLICT %s\n' "$*" >&2; errors=$((errors + 1)); }

ensure_link() {
    local source="$1" destination="$2"
    mkdir -p -- "${destination%/*}"
    if [[ -L "$destination" ]] &&
       [[ "$(readlink -f -- "$destination" 2>/dev/null)" == "$(readlink -f -- "$source")" ]]; then
        ok "$destination"
    elif [[ -e "$destination" || -L "$destination" ]]; then
        fail "$destination already exists and is not the managed link"
        return 1
    elif ln -s -- "$source" "$destination"; then
        ok "$destination -> $source"
    else
        fail "could not create $destination"
        return 1
    fi
}

read_default() {
    local app_dir="$1" kind="$2" name
    [[ -r "$app_dir/default-theme" ]] || { fail "missing $kind default-theme"; return 1; }
    IFS= read -r name < "$app_dir/default-theme"
    [[ "$name" =~ ^[A-Za-z0-9_-]+$ ]] || { fail "invalid $kind default theme: $name"; return 1; }
    printf '%s\n' "$name"
}

initialize_kitty_theme() {
    local app_dir="$config_home/kitty" selector="$config_home/kitty/local-theme.conf"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/kitty" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Kitty local theme already initialized"; return; }
    name="$(read_default "$app_dir" Kitty)" || return
    [[ -f "$app_dir/themes/$name.conf" ]] || { fail "missing Kitty default theme file: $name"; return; }
    temp=$(mktemp "$app_dir/.local-theme.conf.XXXXXX") || { fail 'could not create Kitty selector'; return; }
    printf '%s\n' '# Local theme selection; generated by setup.sh or kitty-theme.' \
        "include themes/$name.conf" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Kitty theme: $name"
}

initialize_rofi_theme() {
    local app_dir="$config_home/rofi" selector="$config_home/rofi/local-theme.rasi"
    local name target temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/rofi" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Rofi local theme already initialized"; return; }
    name="$(read_default "$app_dir" Rofi)" || return
    target="$app_dir/themes/$name/theme.rasi"
    [[ -f "$target" ]] || { fail "missing Rofi default theme: $name"; return; }
    temp=$(mktemp "$app_dir/.local-theme.rasi.XXXXXX") || { fail 'could not create Rofi selector'; return; }
    printf '@theme "%s"\n' "$target" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Rofi theme: $name"
}

initialize_waybar_theme() {
    local app_dir="$config_home/waybar" selector="$config_home/waybar/local-theme.css"
    local name temp
    [[ "$(readlink -f -- "$app_dir" 2>/dev/null)" == "$repo_dir/config/waybar" ]] || return
    [[ -e "$selector" || -L "$selector" ]] && { ok "Waybar local theme already initialized"; return; }
    name="$(read_default "$app_dir" Waybar)" || return
    [[ -f "$app_dir/themes/$name.css" ]] || { fail "missing Waybar default theme: $name"; return; }
    temp=$(mktemp "$app_dir/.local-theme.css.XXXXXX") || { fail 'could not create Waybar selector'; return; }
    printf '@import url("themes/%s.css");\n' "$name" > "$temp"
    mv -- "$temp" "$selector"
    ok "initialized Waybar theme: $name"
}

check_command() {
    local command_name="$1" feature="$2"
    if command -v "$command_name" >/dev/null 2>&1; then
        ok "$command_name ($feature)"
    else
        warn "missing command: $command_name ($feature)"
        missing=$((missing + 1))
    fi
}

printf 'Deploying rice-config from %s\n\n' "$repo_dir"

ensure_link "$repo_dir/config/hypr" "$config_home/hypr"
ensure_link "$repo_dir/config/kitty" "$config_home/kitty"
ensure_link "$repo_dir/config/rofi" "$config_home/rofi"
ensure_link "$repo_dir/config/waybar" "$config_home/waybar"

ensure_link "$repo_dir/scripts/keybind-help" "$bin_dir/keybind-help"
ensure_link "$repo_dir/scripts/kitty-theme.sh" "$bin_dir/kitty-theme"
ensure_link "$repo_dir/scripts/rofi-theme.sh" "$bin_dir/rofi-theme"
ensure_link "$repo_dir/scripts/waybar-nvidia" "$bin_dir/waybar-nvidia"
ensure_link "$repo_dir/scripts/waybar-microphone" "$bin_dir/waybar-microphone"
ensure_link "$repo_dir/scripts/waybar-theme.sh" "$bin_dir/waybar-theme"
ensure_link "$repo_dir/scripts/rofi-apps" "$bin_dir/rofi-apps"

ensure_link "$repo_dir/config/rofi/hidden-applications.desktop" \
    "$data_home/applications/rofi-hidden-applications.desktop"
ensure_link "$repo_dir/config/rofi/system-applications.desktop" \
    "$data_home/applications/rofi-system-applications.desktop"

initialize_kitty_theme
initialize_rofi_theme
initialize_waybar_theme

if [[ "$(readlink -f -- "$config_home/rofi" 2>/dev/null)" == "$repo_dir/config/rofi" ]]; then
    "$config_home/rofi/scripts/hidden-apps.sh" sync || fail 'could not synchronize Hidden applications'
    "$config_home/rofi/scripts/system-apps.sh" sync || fail 'could not synchronize System applications'
fi

printf '\nDependency check\n'
for item in \
    'Hyprland:desktop compositor' 'hyprctl:Hyprland control' 'kitty:terminal' \
    'rofi:application launcher' 'hypridle:idle handling' 'hyprlock:screen locking' \
    'waybar:desktop panel' 'swaync:notification daemon' 'swaync-client:notification controls' \
    'wlctl:Wi-Fi control' 'nmtui:Ethernet control' 'bluetui:Bluetooth control' \
    'wiremix:audio control' 'pw-dump:microphone state' 'wpctl:audio mute control' \
    'powerprofilesctl:power profile control' 'wlogout:power menu' \
    'swayosd-server:on-screen display' 'swayosd-client:media and hardware keys' \
    'playerctl:media control' 'brightnessctl:brightness control' 'thunar:file manager' 'jq:JSON processing' \
    'gio:desktop-entry launching' 'hyprshot:screenshots (external)' 'grim:screenshot capture' \
    'slurp:geometry selection' 'wl-copy:clipboard screenshots' 'notify-send:notifications' \
    'xdg-user-dir:pictures directory'; do
    check_command "${item%%:*}" "${item#*:}"
done
if command -v hyprpolkitagent >/dev/null 2>&1 || [[ -x /usr/libexec/hyprpolkitagent ]]; then
    ok 'Hyprland polkit agent'
else
    warn 'missing Hyprland polkit agent executable'
    missing=$((missing + 1))
fi
if command -v qtpaths6 >/dev/null 2>&1 &&
   [[ -f "$(qtpaths6 --query QT_INSTALL_QML)/org/hyprland/style/qmldir" ]]; then
    ok 'Hyprland Qt/QML style module'
else
    warn 'missing Hyprland Qt/QML style module: org.hyprland.style'
    missing=$((missing + 1))
fi
command -v hyprpicker >/dev/null 2>&1 || warn 'optional command missing: hyprpicker (Hyprshot freeze mode)'
case ":$PATH:" in
    *:"$bin_dir":*) ;;
    *) warn "$bin_dir is not on PATH; desktop gateway commands will not launch" ;;
esac

printf '\nValidation\n'
if command -v desktop-file-validate >/dev/null 2>&1; then
    if desktop-file-validate "$repo_dir/config/rofi/hidden-applications.desktop" \
        "$repo_dir/config/rofi/system-applications.desktop"; then
        ok 'Rofi gateway desktop entries'
    else
        fail 'Rofi gateway desktop-entry validation failed'
    fi
fi
if command -v Hyprland >/dev/null 2>&1 && [[ -r "$config_home/hypr/hyprland.conf" ]]; then
    if Hyprland --verify-config --config "$config_home/hypr/hyprland.conf" >/dev/null 2>&1; then
        ok 'Hyprland configuration'
    else
        fail 'Hyprland configuration validation failed'
    fi
fi
kitty_validation=""
if command -v kitty >/dev/null 2>&1 && [[ -r "$config_home/kitty/kitty.conf" ]]; then
    if kitty_validation=$(KITTY_CONFIG_TO_CHECK="$config_home/kitty/kitty.conf" kitty +runpy '
import os, sys
from kitty.config import load_config
b = []
load_config(os.environ["KITTY_CONFIG_TO_CHECK"], accumulate_bad_lines=b)
sys.exit(bool(b))
' 2>&1) && [[ -z "$kitty_validation" ]]; then
        ok 'Kitty configuration'
    else
        [[ -z "$kitty_validation" ]] || warn "Kitty configuration diagnostics: $kitty_validation"
        fail 'Kitty configuration validation failed'
    fi
fi
if command -v rofi >/dev/null 2>&1 && [[ -r "$config_home/rofi/config.rasi" ]]; then
    if rofi -config "$config_home/rofi/config.rasi" -dump-config >/dev/null 2>&1; then
        ok 'Rofi configuration'
    else
        fail 'Rofi configuration validation failed'
    fi
fi
if [[ -r "$config_home/waybar/config.jsonc" ]] &&
   [[ "$(readlink -f -- "$config_home/waybar" 2>/dev/null)" == "$repo_dir/config/waybar" ]]; then
    waybar_json_valid=true
    if command -v json5 >/dev/null 2>&1; then
        for waybar_json in "$config_home/waybar/config.jsonc" "$config_home/waybar/modules/"*.jsonc; do
            json5 --validate "$waybar_json" >/dev/null 2>&1 || waybar_json_valid=false
        done
    elif command -v jq >/dev/null 2>&1; then
        jq empty "$config_home/waybar/config.jsonc" "$config_home/waybar/modules/"*.jsonc || waybar_json_valid=false
    else
        waybar_json_valid=false
    fi
    if "$waybar_json_valid"; then
        ok 'Waybar JSONC configuration'
    else
        fail 'Waybar JSONC configuration validation failed'
    fi

    if command -v python3 >/dev/null 2>&1 &&
       python3 -c 'import gi; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk' >/dev/null 2>&1; then
        if python3 -c 'import gi, sys; gi.require_version("Gtk", "3.0"); from gi.repository import Gtk; provider = Gtk.CssProvider(); provider.load_from_path(sys.argv[1])' "$config_home/waybar/style.css"; then
            ok 'Waybar GTK3 stylesheet'
        else
            fail 'Waybar GTK3 stylesheet validation failed'
        fi
    else
        fail 'cannot validate Waybar GTK3 stylesheet: Python GObject GTK3 bindings unavailable'
    fi
fi
printf '\n'
if (( errors )); then
    printf 'Deployment completed with %d conflict/error(s).\n' "$errors" >&2
    exit 1
fi
printf 'Deployment complete. Missing dependency count: %d.\n' "$missing"
