# Monitor configuration
monitor=,preferred,auto,auto

# Input configuration
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    natural_scroll = no

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0
}

# Layout configuration
general {
    layout = dwindle
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

# Environment variables
env = XCURSOR_SIZE,24
