pulse.rules = [
    {
        matches = [
            { application.process.binary = "spotify" }
        ]
        actions = {
            update-props = {
                application.name = "Spotify"
                application.icon_name = "spotify-client"
            }
        }
    }
]
