# Hyprland configuration index
source = ~/.config/hypr/hyprland.d/base.conf
source = ~/.config/hypr/hyprland.d/keybinds.conf
source = ~/.config/hypr/hyprland.d/startup.conf
source = ~/.config/hypr/hyprland.d/rules.conf
source = ~/.config/rice-theme/selectors/hyprland.conf
