# Black palette with slight background transparency.
foreground #e8e8e8
background #000000
background_opacity 0.92

selection_foreground #e8e8e8
selection_background #2d374d
url_color #728DBE
visual_bell_color #2d374d

tab_bar_background #000000
active_tab_foreground #728DBE
active_tab_background #000000
inactive_tab_foreground #595959
inactive_tab_background #000000

color0  #000000
color8  #595959
color1  #d94f70
color9  #ff0066
color2  #00c878
color10 #00ff99
color3  #c9a95d
color11 #e8c96b
color4  #728DBE
color12 #91a8d0
color5  #a77bb5
color13 #c395d3
color6  #56aeb8
color14 #70ccd6
color7  #e8e8e8
color15 #ffffff
