#!/usr/bin/env bash

set -euo pipefail

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
selector="$config_dir/local-theme.conf"
default_file="$config_dir/default-theme"
themes_dir="$config_dir/themes"

usage() {
    printf 'Usage: %s {current|list|default|THEME_NAME}\n' "$0"
    printf 'Use default.conf to select the Kitty theme named default.\n'
}

list_themes() {
    local theme
    shopt -s nullglob
    for theme in "$themes_dir"/*.conf; do
        basename "$theme" .conf
    done
}

current_theme() {
    [[ -r "$selector" ]] || {
        printf 'No Kitty theme is selected; run setup.sh or kitty-theme default.\n' >&2
        return 1
    }
    awk '$1 == "include" && $2 ~ /^themes\// { sub(/^themes\//, "", $2); sub(/\.conf$/, "", $2); print $2; exit }' "$selector"
}

default_theme() {
    local name
    [[ -r "$default_file" ]] || {
        printf 'Missing default theme declaration: %s\n' "$default_file" >&2
        return 1
    }
    IFS= read -r name < "$default_file"
    [[ "$name" =~ ^[A-Za-z0-9_-]+$ && -f "$themes_dir/$name.conf" ]] || {
        printf 'Invalid default Kitty theme: %s\n' "$name" >&2
        return 1
    }
    printf '%s\n' "$name"
}

if (( $# != 1 )); then
    usage >&2
    exit 2
fi

case "$1" in
    current)
        current_theme
        exit
        ;;
    list)
        list_themes
        exit
        ;;
    default)
        theme_name="$(default_theme)"
        ;;
    -h|--help)
        usage
        exit
        ;;
    *)
        theme_name=${1%.conf}
        ;;
esac

if [[ "$theme_name" == *[!A-Za-z0-9_-]* || ! -f "$themes_dir/$theme_name.conf" ]]; then
    printf 'Unknown theme: %s\n\nAvailable themes:\n' "$1" >&2
    list_themes >&2
    exit 1
fi

# Validate the complete configuration with the requested selector before it
# can replace the active selector.
check_selector=$(mktemp "$config_dir/.kitty-theme-check.selector.XXXXXX")
check_config=$(mktemp "$config_dir/.kitty-theme-check.config.XXXXXX")
temp_selector=""
cleanup() {
    rm -f -- "$check_selector" "$check_config"
    [[ -z "$temp_selector" ]] || rm -f -- "$temp_selector"
}
trap cleanup EXIT
printf 'include themes/%s.conf\n' "$theme_name" > "$check_selector"
awk -v selector="${check_selector##*/}" '
    $1 == "include" && $2 == "local-theme.conf" { print "include " selector; next }
    { print }
' "$config_dir/kitty.conf" > "$check_config"

validation_output=""
if ! validation_output=$(KITTY_CONFIG_TO_CHECK="$check_config" kitty +runpy '
import os
import sys
from kitty.config import load_config

bad_lines = []
load_config(os.environ["KITTY_CONFIG_TO_CHECK"], accumulate_bad_lines=bad_lines)
for bad_line in bad_lines:
    print(bad_line, file=sys.stderr)
sys.exit(bool(bad_lines))
' 2>&1); then
    printf '%s\n' "$validation_output" >&2
    printf 'Requested theme is invalid; the active theme was not changed.\n' >&2
    exit 1
fi
if [[ -n "$validation_output" ]]; then
    printf '%s\n' "$validation_output" >&2
    printf 'Requested theme produced Kitty diagnostics; the active theme was not changed.\n' >&2
    exit 1
fi

temp_selector=$(mktemp "$config_dir/.local-theme.conf.XXXXXX")
printf '%s\n' '# Local theme selection; generated by setup.sh or kitty-theme.' \
    "include themes/$theme_name.conf" > "$temp_selector"
mv -- "$temp_selector" "$selector"
temp_selector=""

# SIGUSR1 is Kitty's built-in config reload signal. Prefer the parent Kitty
# exported to shells; fall back to detected Kitty GUI processes.
kitty_pids=()
if [[ "${KITTY_PID:-}" =~ ^[1-9][0-9]*$ ]] && kill -0 "$KITTY_PID" 2>/dev/null; then
    kitty_pids=("$KITTY_PID")
else
    mapfile -t kitty_pids < <(pgrep -x kitty 2>/dev/null || true)
fi

reloaded=0
for kitty_pid in "${kitty_pids[@]}"; do
    if kill -USR1 "$kitty_pid" 2>/dev/null; then
        reloaded=1
    fi
done

if (( reloaded )); then
    printf 'Activated and reloaded Kitty theme: %s\n' "$theme_name"
else
    printf 'Activated Kitty theme: %s (no running Kitty instance to reload)\n' "$theme_name"
fi
